### ISSUE TITLE
Export UV map does not function

### ISSUE THREAD

**Issue by Hunanbean** [makehumancommunity/makehuman#128]
Pressing Export with UV map selected seems to have no function.

Thank you

**Comment by Aranuvir** [comment]
Seems to be some prehistorical code. Should be fixed so far ...

**Comment by Hunanbean** [comment]
Thank you for the quick action.
unfortunately, after updating the two files (please tell me if i missed one) I no longer have the option for UV export, and the lightmap export seems to do nothing.

I have not looked at the code (still don't know enough for it to matter), so i do not know if it was your intent to remove it

Thanks, be well

**Comment by Aranuvir** [comment]
Could any one else check, if we can close this topic?

**Comment by Hunanbean** [comment]
It is working again in the 1.2.0 release. Thank you.
